characterNames = [
    "banjoandkazooie",
    "bayonetta",
    "bowser",
    "bowserjr",
    "byleth",
    "captainfalcon",
    "charizard",
    "chrom",
    "cloud",
    "corrin",
    "daisy",
    "darkpit",
    "darksamus",
    "diddykong",
    "donkeykong",
    "drmario",
    "duckhunt",
    "falco",
    "fox",
    "ganondorf",
    "greninja",
    "hero",
    "iceclimbers",
    "ike",
    "incineroar",
    "inkling",
    "isabelle",
    "ivysaur",
    "jigglypuff",
    "joker",
    "kazuya",
    "ken",
    "kingdedede",
    "kingkrool",
    "kirby",
    "link",
    "littlemac",
    "lucario",
    "lucas",
    "lucina",
    "luigi",
    "mario",
    "marth",
    "megaman",
    "metaknight",
    "mewtwo",
    "miibrawler",
    "miigunner",
    "miiswordfighter",
    "minmin",
    "mrgameandwatch",
    "mythra",
    "ness",
    "olimar",
    "pacman",
    "palutena",
    "peach",
    "pichu",
    "pikachu",
    "piranhaplant",
    "pit",
    "pokemontrainer",
    "pyra",
    "pyraandmythra",
    "richter",
    "ridley",
    "rob",
    "robin",
    "rosalinaandluma",
    "roy",
    "ryu",
    "samus",
    "sephiroth",
    "sheik",
    "shulk",
    "simon",
    "snake",
    "sonic",
    "sora",
    "squirtle",
    "steve",
    "terry",
    "toonlink",
    "villager",
    "wario",
    "wiifittrainer",
    "wolf",
    "yoshi",
    "younglink",
    "zelda",
    "zerosuitsamus"
]

aliases = [
    ["banjo", "banjoandkazooie"],
    ["bayo", "bayonetta"],
    ["larry", "bowserjr"],
    ["wendy", "bowserjr"],
    ["iggy", "bowserjr"],
    ["morton", "bowserjr"],
    ["lemmy", "bowserjr"],
    ["ludwig", "bowserjr"],
    ["falcon", "captainfalcon"],
    ["zard", "charizard"],
    ["diddy", "diddykong"],
    ["dk", "donkeykong"],
    ["doc", "drmario"],
    ["duckhuntdog", "duckhunt"],
    ["ganon", "ganondorf"],
    ["ics", "iceclimbers"],
    ["incin", "incineroar"],
    ["ivy", "ivysaur"],
    ["dedede", "kingdedede"],
    ["ddd", "kingdedede"],
    ["krool", "kingkrool"],
    ["mac", "littlemac"],
    ["mk", "metaknight"],
    ["m2", "mewtwo"],
    ["brawler", "miibrawler"],
    ["gunner", "miigunner"],
    ["swordfighter", "miiswordfighter"],
    ["swordie", "miiswordfighter"],
    ["g&w", "mrgameandwatch"],
    ["gnw", "mrgameandwatch"],
    ["pac", "pacman"],
    ["palu", "palutena"],
    ["pika", "pikachu"],
    ["plant", "piranhaplant"],
    ["pt", "pokemontrainer"],
    ["trainer", "pokemontrainer"],
    ["puff", "jigglypuff"],
    ["aegis", "pyraandmythra"],
    ["pythra", "pyraandmythra"],
    ["pyramythra", "pyraandmythra"],
    ["belmont", "richter"],
    ["rosa", "rosalinaandluma"],
    ["rosalina", "rosalinaandluma"],
    ["seph", "sephiroth"],
    ["alex", "steve"],
    ["enderman", "steve"],
    ["zombie", "steve"],
    ["tink", "toonlink"],
    ["villy", "villager"],
    ["wft", "wiifittrainer"],
    ["wiifit", "wiifittrainer"],
    ["yink", "younglink"],
    ["zss", "zerosuitsamus"]
]

aliasMap = new Map();

for(i = 0; i < aliases.length; i++) {
    aliasMap.set(aliases[i][0], aliases[i][1]);
}